language: java
jdk: 
  - oraclejdk9
services:
  - docker

env:
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/user  
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.3 BUILD_TARGET=./monolithic/repository/user

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
  on: 
    all_branches: true