language: java
jdk:
- openjdk8
services:
- docker
env:
  matrix:
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.3 BUILD_TARGET=./monolithic/repository/user
  global:
    secure: vEIgXIjktpyn+TyPaYdRkDUUq9uxBg8gjnfpKQMpNQOV8afyBZEe3C9M+JBjCCC5ayZzrLNAwVFYtxWjCw7buJy94b8SHDrBAFnWUPOTB/1gB+84nFsRqhfuoNPHiNZLvUID4A0UUAHSDotdi23XjmCRzQ5gqCZ28mMopmnSTiswKjQQxwTkaPJyQpYAqiAlsDlxKtmedCb3DYE2GPcja/9iVwzVdxL1Mc372ET77UHyCxiGI+cQGzmx8NUDuk2dDE+Fr5PpXFMEzK5FAkWPEC+oh6sTtFI4a+73MwZtvMYvg4AiFKDp1d+XDz57vo8CPonAlKu4wA66JW5i5Xtt8mAcbL0JD/S5SqQW9pMpyS15zaDvSczySuCAp7TfWzCA63oU3n8ac9RpP5s3L+FDomusXuyxjct4gUFcpqCIbcfxiVSpPKqcLdVHqSGGHFN1bQfTPEnoQDsFBL49KR9oEfhdHNj43mfLl4ltIxTle1P7TN+jbJQxgH+ACbMVpLXDo5aw4gQ6vGMOf+Dr9ASauP0lA76h2KExgm/uJ/0Q/828y8VfltWfjmspe9hLYlZdQj/eRX1EWK3Wmq+z3oRvAuMXblIc7VXOxYojhg/OAG38olmKnSLbYAEP4DX/Ry0zNI/IwDlt3q/pF+rTCOhmGbLkgSQcgCCtT7AJ7zVKPOQ=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
deploy:
  provider: script
  script: echo \"${DOCKER_PASSWORD}\"
  on:
    all_branches: true
