language: java
jdk:
- openjdk8
services:
- docker
env:
  matrix:
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.5 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.3 BUILD_TARGET=./monolithic/repository/user
  global:
  - secure: DkdlQGJOU3YxiCKfW6u2g1p4PV179Pt3HwZSjSTumAtsaWdk7OeIBWdLfgF3AjKlThDm+POJKRjyUNXhm2OGx257mnyYmGKDvLUJOmsYxjZAnmhzXoD+XuZsUfuNsdQomd7YxUsu6fk3UqA36BeTEGEN0b+mAKAlbSVj87e7Y3ANjsIAa11KEyAKe+AkoTidxI4h68LkxyTtHkKbB+CFOhmmNY0KOFUPFA05xV21pWTUem+rgtlylbeDs3VoqD0pqVERgNjlIiws7qwtKimWpqPQG2dkxjR5TGxjNg+6Z7U4iDw2ELDI3+IVRXp2ib+jK4pMO4YcoTcnwtlTcUBaLkBCozHuQNjnnmD9IqOyZDJkuPs7XgDldr4ATsQTKBTEMNFw2cGiZtJvEv6xvUfTDHwF58UO1s0RJVzub7fPUJles7NNeWjY4HSjbxqagXyc889qLz33dcnvchOkF4k82r3hyZUDATHL4Lm+hkZa7iNHCXbiMG6aPXmOXiHkRYYOF6Vpsz7+59LQ2G3QN9op0CKkZWeYxGL+dhwBRWaeLmC0zgA9i6hDdBm2YX9M0T+wAk6ud5/5ykiVDeKucbenUdbPqFvVLEWBH5g9UBsmjQJMV/22cvKTUw2C9eK3YoD4gQ08Z5EuR4um37RSoMlaHP9T9IPEpL+uxghkLKVfCzQ=
  - secure: p2q1zxS5ayu0TvSlssqWM+oBhSOm9Dpxw11FsMSch6ZcitYo2ts/z/wllBV6tlYmo25CA3JzuIbUblY+BIBNKmWyzBeWWZNV/E8yfQ/cr2s+8ysB3W5GfsqRzzKs/OBKyO/yEn0F+QP1Nvpcsrfl66B3Fg2InMK7I6s6U6/wei3h+MiALv/JWzJqoKQlzMWQdjpcCoG9B2wpfmBEh8ILUVrD/tbc/6R4s3rPBE0buXb9StUBHe/2NxBtdwF5+NKIXJO5qYfvk6aSempT3/pfJon/f4JkqQrFJQG6ekVm6mZ1Wi8P8CZToTroI21Cb+HeIwP/S9eKZo1bByomkWvHg1EPjhJQDeCZsxnlDPBMt62StF2ZuuTRf8RiPA/hKQoYVobsRb7TT1rR5r2GMX8YAzApGtrbFoljUxFUSYqelq9VYJBPbchlHQ6qTOmgH4jw64QFg47omFcQ1um4NhJSvLOWsGtp/HYaVUEE09UZrk6G68/63v9DhTpbLQfLZY48fj61SEIot4GzGOBF8ljQO9EcKVYf14bIo/ug4zpx42L5nIZXpxKY5pHr35k1BgJFcsCWZirvDq/to8WiOxHbpmnpzqFHIOhbJkYXbF59MGv2kaUIut4Xme7M+B6g1cKrhpstoSAj2coXJDGDqf7lrWcps4SDXQ0UTy2khxfrWTs=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login -u \"${DOCKER_LOGIN}\" --password-stdin"
  on:
    all_branches: true
